#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
# Disable threading to prevent an issue with django-debug-toolbar's profiler
# See https://github.com/jazzband/django-debug-toolbar/issues/1875
exec python manage.py runserver_plus --nothreading 0.0.0.0:8000
