/* tslint:disable */
/* eslint-disable */
/**
 * Democrasite API
 * Documentation of API endpoints of Democrasite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Vote,
} from '../models/index';
import {
    VoteFromJSON,
    VoteToJSON,
} from '../models/index';

export interface VoteCreateRequest {
    vote: Vote;
}

/**
 *
 */
export class VoteApi extends runtime.BaseAPI {

    /**
     */
    async voteCreateRaw(requestParameters: VoteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vote>> {
        if (requestParameters.vote === null || requestParameters.vote === undefined) {
            throw new runtime.RequiredError('vote','Required parameter requestParameters.vote was null or undefined when calling voteCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/vote/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VoteToJSON(requestParameters.vote),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VoteFromJSON(jsonValue));
    }

    /**
     */
    async voteCreate(requestParameters: VoteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vote> {
        const response = await this.voteCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
