# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Every Monday
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for `Dockerfiles` in the `compose/local/django` directory
    # and in the compose/production subdirectories
    directories: "compose/*/*/"
    # Every Monday
    schedule:
      interval: "weekly"
    # Ignore minor version updates (3.12 -> 3.13) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups: docker

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Every Monday
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
