# Generated by Django 5.1.6 on 2025-07-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='activitypub.person')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='activitypub.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('following', 'follower'), name='unique_follow', violation_error_code="Can't follow a person more than once")],
            },
        ),
    ]
