# Generated by Django 5.2.10 on 2026-02-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0002_historicalnote_historicallike_historicalperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='People this person is following', related_name='followers', through='activitypub.Follow', through_fields=('follower', 'following'), to='activitypub.person'),
        ),
    ]
