/* tslint:disable */
/* eslint-disable */
/**
 * Democrasite API
 * Documentation of API endpoints of Democrasite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRequest } from './UserRequest';
import {
    UserRequestFromJSON,
    UserRequestFromJSONTyped,
    UserRequestToJSON,
} from './UserRequest';

/**
 *
 * @export
 * @interface BillRequest
 */
export interface BillRequest {
    /**
     *
     * @type {UserRequest}
     * @memberof BillRequest
     */
    author: UserRequest;
    /**
     *
     * @type {string}
     * @memberof BillRequest
     */
    status: string;
    /**
     *
     * @type {Date}
     * @memberof BillRequest
     */
    statusChanged?: Date;
    /**
     *
     * @type {string}
     * @memberof BillRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof BillRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the BillRequest interface.
 */
export function instanceOfBillRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "author" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function BillRequestFromJSON(json: any): BillRequest {
    return BillRequestFromJSONTyped(json, false);
}

export function BillRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'author': UserRequestFromJSON(json['author']),
        'status': json['status'],
        'statusChanged': !exists(json, 'status_changed') ? undefined : (new Date(json['status_changed'])),
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function BillRequestToJSON(value?: BillRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'author': UserRequestToJSON(value.author),
        'status': value.status,
        'status_changed': value.statusChanged === undefined ? undefined : (value.statusChanged.toISOString()),
        'name': value.name,
        'description': value.description,
    };
}
