/* tslint:disable */
/* eslint-disable */
/**
 * Democrasite API
 * Documentation of API endpoints of Democrasite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VoteRequest
 */
export interface VoteRequest {
    /**
     *
     * @type {boolean}
     * @memberof VoteRequest
     */
    support: boolean;
}

/**
 * Check if a given object implements the VoteRequest interface.
 */
export function instanceOfVoteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "support" in value;

    return isInstance;
}

export function VoteRequestFromJSON(json: any): VoteRequest {
    return VoteRequestFromJSONTyped(json, false);
}

export function VoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'support': json['support'],
    };
}

export function VoteRequestToJSON(value?: VoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'support': value.support,
    };
}
