/* tslint:disable */
/* eslint-disable */
/**
 * Democrasite API
 * Documentation of API endpoints of Democrasite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PullRequest
 */
export interface PullRequest {
    /**
     *
     * @type {number}
     * @memberof PullRequest
     */
    readonly number: number;
    /**
     *
     * @type {string}
     * @memberof PullRequest
     */
    readonly title: string;
    /**
     * Lines added
     * @type {number}
     * @memberof PullRequest
     */
    readonly additions: number;
    /**
     * Lines removed
     * @type {number}
     * @memberof PullRequest
     */
    readonly deletions: number;
    /**
     * URL to the diff of the pull request
     * @type {string}
     * @memberof PullRequest
     */
    readonly diffUrl: string;
    /**
     *
     * @type {Date}
     * @memberof PullRequest
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the PullRequest interface.
 */
export function instanceOfPullRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "additions" in value;
    isInstance = isInstance && "deletions" in value;
    isInstance = isInstance && "diffUrl" in value;
    isInstance = isInstance && "created" in value;

    return isInstance;
}

export function PullRequestFromJSON(json: any): PullRequest {
    return PullRequestFromJSONTyped(json, false);
}

export function PullRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'number': json['number'],
        'title': json['title'],
        'additions': json['additions'],
        'deletions': json['deletions'],
        'diffUrl': json['diff_url'],
        'created': (new Date(json['created'])),
    };
}

export function PullRequestToJSON(value?: PullRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

    };
}
