# Generated by Django 4.2.10 on 2024-02-25 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pr_num', models.IntegerField(verbose_name='Pull request number')),
                ('additions', models.IntegerField(help_text='Lines added')),
                ('deletions', models.IntegerField(help_text='Lines removed')),
                ('sha', models.CharField(help_text='Unique identifier of PR commit', max_length=40)),
                ('state', models.CharField(choices=[('o', 'Open'), ('a', 'Approved'), ('r', 'Rejected'), ('f', 'Not Enough Votes'), ('c', 'PR Closed')], default='o', help_text='The current status of the bill', max_length=1)),
                ('constitutional', models.BooleanField(default=False, help_text='True iff this bill is an amendment to the constitution')),
                ('prop_date', models.DateTimeField(auto_now_add=True, verbose_name='date proposed')),
                ('author', models.ForeignKey(default=34, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webiscite.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', through='webiscite.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('pr_num', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Pull request number')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], help_text='State of the PR on Github', max_length=6)),
                ('additions', models.IntegerField(help_text='Lines added')),
                ('deletions', models.IntegerField(help_text='Lines removed')),
                ('sha', models.CharField(help_text='Unique identifier of PR commit', max_length=40)),
                ('prop_date', models.DateTimeField(auto_now_add=True, verbose_name='date proposed')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deletions',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pr_num',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sha',
        ),
        migrations.AlterField(
            model_name='bill',
            name='constitutional',
            field=models.BooleanField(default=False, help_text='True if this bill is an amendment to the constitution'),
        ),
        migrations.AddField(
            model_name='bill',
            name='pull_request',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='webiscite.pullrequest'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'o')), fields=('pull_request',), name='unique_open_pull_request', violation_error_message='A Bill for this pull request is already open'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='sha',
            field=models.CharField(help_text='Unique identifier of PR commit', max_length=40, unique=True),
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='prop_date',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='prop_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='submit_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='bill',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='pr_num',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Pull request number'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='diff_url',
            field=models.URLField(default='https://github.com/mfosterw/cookiestocracy/pull/64/files', help_text='URL to the diff of the pull request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
