# Generated by Django 3.1.11 on 2021-05-30 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("pr_num", models.IntegerField(verbose_name="pull request")),
                ("additions", models.IntegerField()),
                ("deletions", models.IntegerField()),
                ("sha", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("o", "Open"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                            ("f", "Not Enough Votes"),
                            ("c", "PR Closed"),
                        ],
                        default="o",
                        max_length=1,
                    ),
                ),
                (
                    "constitutional",
                    models.BooleanField(
                        default=False,
                        help_text="This is true only for amendments to the constitution",
                    ),
                ),
                (
                    "prop_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date proposed"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "no_votes",
                    models.ManyToManyField(
                        blank=True, related_name="no_votes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "yes_votes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="yes_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
