# Generated by Django 4.2.10 on 2024-02-25 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', model_utils.fields.StatusField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Not Enough Votes'), ('closed', 'PR Closed')], default='open', help_text='The current status of the bill', max_length=10, no_check_for_status=True)),
                ('constitutional', models.BooleanField(default=False, help_text='True if this bill is an amendment to the constitution')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Pull request number')),
                ('title', models.CharField(max_length=100)),
                ('additions', models.IntegerField(help_text='Lines added')),
                ('deletions', models.IntegerField(help_text='Lines removed')),
                ('diff_url', models.URLField(help_text='URL to the diff of the pull request')),
                ('author_name', models.CharField(max_length=100)),
                ('sha', models.CharField(help_text='Unique identifier of PR commit', max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webiscite.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webiscite.pullrequest'),
        ),
        migrations.AddField(
            model_name='bill',
            name='submit_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='bill',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', through='webiscite.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('pull_request',), name='unique_open_pull_request', violation_error_message='A Bill for this pull request is already open'),
        ),
    ]
