# Generated by Django 3.1.11 on 2021-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webiscite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="additions",
            field=models.IntegerField(help_text="Lines added"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="constitutional",
            field=models.BooleanField(
                default=False,
                help_text="True iff this bill is an amendment to the constitution",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="deletions",
            field=models.IntegerField(help_text="Lines removed"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="pr_num",
            field=models.IntegerField(verbose_name="Pull request number"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="sha",
            field=models.CharField(
                help_text="Unique identifier of PR commit", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="state",
            field=models.CharField(
                choices=[
                    ("o", "Open"),
                    ("a", "Approved"),
                    ("r", "Rejected"),
                    ("f", "Not Enough Votes"),
                    ("c", "PR Closed"),
                ],
                default="o",
                help_text="The current status of the bill",
                max_length=1,
            ),
        ),
    ]
