# Generated by Django 5.1.6 on 2025-03-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('webiscite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='submit_task',
        ),
        migrations.AddField(
            model_name='bill',
            name='_submit_task',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
    ]
