# Generated by Django 5.1.6 on 2025-07-05 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiscite', '0002_remove_bill_submit_task_bill__submit_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('bill', 'user'), name='unique_user_bill_vote', violation_error_code='Only one vote per user per bill allowed'),
        ),
    ]
