# Generated by Django 4.2.9 on 2024-02-12 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webiscite", "0004_alter_bill_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="no_votes",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="yes_votes",
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("support", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webiscite.bill")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="votes",
            field=models.ManyToManyField(
                blank=True, related_name="votes", through="webiscite.Vote", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
