# Generated by Django 5.1.6 on 2025-09-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiscite', '0004_remove_bill_status_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalpullrequest',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
