# Generated by Django 4.2.9 on 2024-02-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webiscite", "0005_remove_bill_no_votes_remove_bill_yes_votes_vote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "pr_num",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Pull request number",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author_name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[("closed", "Closed"), ("open", "Open")],
                        help_text="State of the PR on Github",
                        max_length=6,
                    ),
                ),
                ("additions", models.IntegerField(help_text="Lines added")),
                ("deletions", models.IntegerField(help_text="Lines removed")),
                (
                    "sha",
                    models.CharField(help_text="Unique identifier of PR commit", max_length=40),
                ),
                (
                    "prop_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="date proposed"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bill",
            name="additions",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="deletions",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="pr_num",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="sha",
        ),
        migrations.AlterField(
            model_name="bill",
            name="constitutional",
            field=models.BooleanField(
                default=False,
                help_text="True if this bill is an amendment to the constitution",
            ),
        ),
    ]
