# Generated by Django 5.2.11 on 2026-02-16 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('webiscite', '0005_alter_bill_name_alter_historicalbill_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='unique_open_pull_request',
        ),
        migrations.AddField(
            model_name='historicalpullrequest',
            name='draft',
            field=models.BooleanField(default=False, help_text='Whether the pull request is a draft on GitHub'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='draft',
            field=models.BooleanField(default=False, help_text='Whether the pull request is a draft on GitHub'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Not Enough Votes'), ('closed', 'PR Closed')], default='open', help_text='The current status of the bill', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Not Enough Votes'), ('closed', 'PR Closed')], default='open', help_text='The current status of the bill', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'draft'])), fields=('pull_request',), name='unique_active_pull_request', violation_error_message='A Bill for this pull request is already active'),
        ),
    ]
