# Generated by Django 4.2.9 on 2024-02-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webiscite", "0006_pullrequest_remove_bill_additions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="pull_request",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.PROTECT, to="webiscite.pullrequest"
            ),
            preserve_default=False,
        ),
    ]
