# Generated by Django 5.2.11 on 2026-02-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('webiscite', '0006_remove_bill_unique_open_pull_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='_submit_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
        ),
    ]
