# Generated by Django 4.2.9 on 2024-02-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webiscite", "0007_bill_pull_request_bill_unique_open_pull_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="pr_num",
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name="Pull request number"),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="sha",
            field=models.CharField(help_text="Unique identifier of PR commit", max_length=40, unique=True),
        ),
    ]
