# Generated by Django 4.2.9 on 2024-02-19 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webiscite", "0009_rename_timestamp_vote_time_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pullrequest",
            old_name="pr_num",
            new_name="number",
        ),
    ]
