# Generated by Django 4.2.9 on 2024-02-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webiscite", "0010_rename_pr_num_pullrequest_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="diff_url",
            field=models.URLField(
                default="https://github.com/mfosterw/cookiestocracy/pull/64/files",
                help_text="URL to the diff of the pull request",
            ),
            preserve_default=False,
        ),
    ]
